**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [95]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
a = int(input("Enter no of rows"))
b = int(input("enter no of columns"))
m = np.random.rand(a,b)
print(m)
print(np.mean(m))

Enter no of rows3
enter no of columns4
[[0.67326345 0.01596944 0.60884307 0.76609425]
 [0.38307903 0.59767907 0.31596701 0.55079527]
 [0.74095776 0.44634576 0.31619954 0.34416133]]
0.4799462481617964


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
a = int(input("Enter no of rows"))
b = int(input("enter no of columns"))
m = np.ones((a,b))
#m
m[1:-1, 1:-1] = 0
m
#Code here

Enter no of rows4
enter no of columns5


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
n =10
np.linspace(0,1, n+1, endpoint= False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
m =np.tile(np.arange(5), (5,2))
m

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
vector = np.random.randint(0, 100, (10,2))
point = np.array([2,3])
distances = np.sqrt(np.sum((vector - point)**2, axis= 1))
distance_marix = distances.astype(int)
print(distance_marix)


[ 79  67 107  83  29  58  45  94  66  81]


`###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
np.unravel_index(99, (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
a = input("Enter arrar with space in numbers")
arr = np.array(a.split(), dtype = float)[::-1]
arr

Enter arrar with space in numbers3 5 7 8 12 45 53


array([53., 45., 12.,  8.,  7.,  5.,  3.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here
a = np.array([1, 2])
print("element count {}".format(a.size))

element count 2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here
a = np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278])
softmax_arr = np.exp(a)/np.sum(np.exp(a))
softmax_arr

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here
def vertical_stack(a, b, *args):
  final = np.vstack((a, b, *args))
  return final



In [ ]:
a= np.array([[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]])

b= np.array([[1,1,1,1,1],
 [1,1,1,1,1]])

c= np.array([[0.10117373, 0.1677244, 0.73764059, 0.83166097, 0.48985695],
 [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

In [ ]:
m = vertical_stack(a, b)
m


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [119]:
#Code here
from datetime import datetime
def find_dates(strt_date, end_date):
  if not(isinstance(strt_date, str) and isinstance(end_date, str)):
    raise TypeError("Strt and end date should be string")

  try:
    strt_date_dt = datetime.strptime(strt_date, '%Y-%m-%d')
    end_date_dt = datetime.strptime(end_date, '%Y-%m-%d')
  except ValueError:
    raise ValueError("Date should be in YYYY-MM-D format")

  if strt_date_dt > end_date_dt or strt_date_dt.year != end_date_dt.year:
    raise ValueError("Start date should bee lesser than end date and both should belong to same year")

  strt_np = np.datetime64(strt_date_dt.date())
  num_days = (end_date_dt - strt_date_dt).days + 1
  #dates = np.array([strt_np + np.timedelta64(i, 'D') for i in range(num_days)], dtype = "np.datetime64[D]")
  dates = np.array([strt_np + np.timedelta64(i, 'D') for i in range(num_days)], dtype='datetime64[D]')
  return dates


In [120]:
res = find_dates(strt_date= '2020-11-25', end_date= '2020-11-30')
res

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:

#code here
m
t = m - np.mean(m, axis = 1, keepdims= True)
t

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [ ]:
arr[:, [0,1]] = arr[:, [1,0]]

In [ ]:
arr

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [ ]:
arr[[0,1], :] = arr[[1,0], :]

In [ ]:
arr

array([[5, 4, 6],
       [2, 1, 3],
       [8, 7, 9]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
# #Code here
# l = [1, 2, 3, 4, 5, 6, 7, 8]
# p = [-1 for i in l if i%2!= 0]
# p

[-1, -1, -1, -1]

In [ ]:
list(map(lambda x: -1 if x%2!=0 else x, l))

[-1, 2, -1, 4, -1, 6, -1, 8]

In [ ]:
arr[arr % 2 == 1]= -1
arr

array([[-1,  4,  6],
       [ 2, -1, -1],
       [ 8, -1, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

In [ ]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

result = np.max((a,b), axis = 0)
result

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[1233, 2383, 1887, 8993,  149],
       [9539,  424, 3956, 6752, 7074],
       [9746, 1116, 4981, 1826, 8306],
       [4638, 3262, 6826, 5527, 5637],
       [6354, 5136, 7578, 8056, 6371],
       [8550, 3741, 2237, 7958, 7853],
       [7147, 7731, 8533, 7280,  309],
       [7942, 9146, 6557, 8501, 8076]])

In [ ]:
#Code here
arr1[:, ::2]

array([[1233, 1887,  149],
       [9539, 3956, 7074],
       [9746, 4981, 8306],
       [4638, 6826, 5637],
       [6354, 7578, 6371],
       [8550, 2237, 7853],
       [7147, 8533,  309],
       [7942, 6557, 8076]])

In [ ]:
#normalise the array
arr1  - np.min(arr1, axis = 0, keepdims= True)/(np.max(arr1, axis = 0, keepdims= True)- np.min(arr1, axis = 0, keepdims = True))

array([[1232.85516269, 2382.9513873 , 1886.71606982, 8992.74522115,
         148.98173348],
       [9538.85516269,  423.9513873 , 3955.71606982, 6751.74522115,
        7073.98173348],
       [9745.85516269, 1115.9513873 , 4980.71606982, 1825.74522115,
        8305.98173348],
       [4637.85516269, 3261.9513873 , 6825.71606982, 5526.74522115,
        5636.98173348],
       [6353.85516269, 5135.9513873 , 7577.71606982, 8055.74522115,
        6370.98173348],
       [8549.85516269, 3740.9513873 , 2236.71606982, 7957.74522115,
        7852.98173348],
       [7146.85516269, 7730.9513873 , 8532.71606982, 7279.74522115,
         308.98173348],
       [7941.85516269, 9145.9513873 , 6556.71606982, 8500.74522115,
        8075.98173348]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here
def nth_largest(arr, n):
  if not isinstance(arr, np.ndarray) or arr.ndim != 1:
    raise ValueError("given array must a numpy array with 1 dimension")
  if n > len(arr) or n < 1:
    raise ValueError("given index is not available in the array")
  return np.sort(arr)[-n]

In [105]:
#Code here
def nth_largest_v2(arr, n):
  if not isinstance(arr, np.ndarray) or arr.ndim != 1:
    raise ValueError("given array must a numpy array with 1 dimension")
  if n > len(arr) or n < 1:
    raise ValueError("given index is not available in the array")
  return np.partition(arr, n)[-n]

In [ ]:
arr = np.array([12, 34, 40, 7, 1, 0])
element = nth_largest(arr, 2)
element.item()

34

In [107]:
arr = np.array([12, 34, 40, 7, 1, 0])
element = nth_largest_v2(arr, 2)
element.item()

34

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here
a = np.array([1,2,3])
res = np.concatenate([np.repeat(a,3), np.tile(a, 3)])
res

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [87]:
f = (np.ones((3,1), dtype = int)*a).ravel(order= 'F')
g = np.tile(a, 3)
h = np.concatenate([f, g])
h

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [92]:
k = np.stack([a]*3).ravel(order = "F")
l = np.tile(a, 3)
k,l

(array([1, 1, 1, 2, 2, 2, 3, 3, 3]), array([1, 2, 3, 1, 2, 3, 1, 2, 3]))

In [97]:
np.vstack([a]*3).ravel(order = 'F')

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])