In [2]:
import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [4]:
# code here
arr = np.array(
    [[92, 90, 74],
    [ 6, 63, 93],
    [15, 93, 96],
    [70, 60, 48]])

np.sort(arr)

array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [3]:
arr = np.array(
    [[92, 90, 74],
    [ 6, 63, 93],
    [15, 93, 96],
    [70, 60, 48]])
sorted_index = np.argsort(arr[:,1])
arr[sorted_index]
#

array([[70, 60, 48],
       [ 6, 63, 93],
       [92, 90, 74],
       [15, 93, 96]])

In [4]:
#using structured arrays
#not working
arr = np.array(
    [[92, 90, 74],
    [ 6, 63, 93],
    [15, 93, 96],
    [70, 60, 48]], dtype=[('a', 'i4'),('b', 'i4'),('c', 'i4')])
np.sort(arr, order='b')

array([[(74, 74, 74), (90, 90, 90), (92, 92, 92)],
       [( 6,  6,  6), (63, 63, 63), (93, 93, 93)],
       [(15, 15, 15), (93, 93, 93), (96, 96, 96)],
       [(48, 48, 48), (60, 60, 60), (70, 70, 70)]],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4')])

In [8]:
#based on row max- ascending
arr = np.array(
    [[92, 90, 74],
    [ 6, 63, 93],
    [15, 93, 96],
    [70, 60, 48]])
row_max = np.max(arr, axis = 1)
max_position = np.argsort(row_max)
#max_position
arr[max_position]

array([[70, 60, 48],
       [92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96]])

In [18]:
#based on element value
arr = np.array(
    [[92, 90, 74],
    [ 6, 63, 93],
    [15, 93, 96],
    [70, 60, 48]])
np.ravel(arr).sort()
arr

array([[ 6, 15, 48],
       [60, 63, 70],
       [74, 90, 92],
       [93, 93, 96]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [48]:
# code here
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

extra_subject = np.array([41, 87, 72, 36, 92])

#np.concatenate((marks, extra_subject.reshape(-1,1)), axis = 1)
new_marks = np.hstack((marks, extra_subject.reshape(-1, 1)))
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
new_marks = np.vstack((new_marks, rec1, rec2))
sum_marks = np.sum(new_marks, axis =1)
#np.concatenate(())
#np.append(new_marks , values= np.sum(new_marks, axis = 1), axis = 0 )
sum_marks
new_report =  np.hstack((new_marks, sum_marks.reshape(-1,1)))

In [52]:
#iv. Sort the array(non-ascending order) on total marks column
sorted_index = np.argsort(-(new_report[:, -1]))
final_report = new_report[sorted_index]

In [53]:
final_report[sorted_index][0:2]

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [56]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
np.unique(arr, axis = 0) #row wise

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [57]:
np.unique(arr, axis = 1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [59]:
# code here
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
np.flip(marks)

array([[36, 59, 61, 67],
       [78, 29,  9, 82],
       [29, 13, 76, 39],
       [42, 90, 46, 63],
       [33,  9, 10, 13]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [87]:
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

X = 6

In [92]:
# code here
np.where(np.any(arr > X, axis = 1))[0]

array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [64]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(4,7)
arr3 = np.arange(7,10)

In [67]:
# code here
a = np.vstack((arr1, arr2, arr3))
a.ravel()

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [71]:
# code here
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr
np.delete(arr, np.argmin(arr))
np.delete(arr, np.argmax(arr))

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
       244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
       270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [75]:
# code here
arr = np.random.randint(100, 700, 200).reshape((1, 200))
np.clip(arr, a_max= 200, a_min = 100)
np.sort(arr)

print(arr)
print(np.cumsum(arr))

[[181 134 134 580 698 679 369 367 215 579 210 297 694 129 160 287 682 353
  442 680 583 522 160 261 147 407 444 117 226 205 439 237 529 512 676 341
  187 645 472 204 626 176 382 230 563 376 671 649 672 361 513 331 612 143
  254 526 428 574 656 650 416 402 246 341 691 275 108 457 520 325 321 171
  198 371 637 630 549 101 534 593 588 284 338 572 220 179 323 242 105 340
  198 374 147 642 660 287 545 164 565 356 510 130 110 198 450 330 322 438
  109 114 369 295 694 158 640 447 374 575 570 637 430 340 131 648 226 104
  647 159 483 236 420 676 449 171 450 311 328 544 217 557 186 544 247 653
  345 670 146 377 560 277 167 596 280 300 111 571 429 248 486 183 663 533
  433 545 361 612 359 421 685 127 464 618 489 481 421 688 502 687 475 425
  553 105 447 424 454 234 337 451 216 159 201 656 393 533 539 130 441 271
  656 452]]
[  181   315   449  1029  1727  2406  2775  3142  3357  3936  4146  4443
  5137  5266  5426  5713  6395  6748  7190  7870  8453  8975  9135  9396
  9543  9950 10394 10511 107

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [83]:
# code here
ar = np.random.random(100)
ar = np.round(ar, 3)

if np.percentile(ar, 0) == np.min(ar):
  print("0 percentile and min is equal")

if np.percentile(ar, 100) == np.max(ar):
  print("100 percentile and max is equal")

np.percentile(ar, 51).item() - np.percentile(ar, 50).item()

0 percentile and min is equal
100 percentile and max is equal


0.0039300000000001

In [29]:
#2nd most frequent element of array
arr = np.array([1, 2, 3, 1, 4, 2, 1, 4, 4, 4])
item, count= np.unique(arr, return_counts= True)
#item, count


sorted_idx = np.argsort(-count)
second_idx = sorted_idx[1]
item[second_idx], count[second_idx]
print(item,count)
print(sorted_idx)

[1 2 3 4] [3 2 1 4]
[3 0 1 2]
